version: 2.1

orbs:
  sls: tillersystems/sls@0.0.7

workflows:
  version: 2
  tagged-build:
    jobs:
      - sls/publish_only:
          package_version: $CIRCLE_TAG
          node_version: "14.17.0"
          ssh_key_fingerprint: "4a:d0:28:34:be:9b:64:02:a3:30:ff:7b:b0:36:b1:5e"
          base_branch: "main"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*$/
